# Generated by Django 3.1.5 on 2021-01-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_awards_batting_bowling_cup_member_opponent_role_type_wicket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Awards',
            new_name='Award',
        ),
    ]
