# Generated by Django 3.1.5 on 2021-02-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210205_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='badge',
            field=models.ImageField(blank=True, default='default profile pic1.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='team',
            name='home',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
