# Generated by Django 3.1.5 on 2021-02-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210205_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='team',
            name='home',
        ),
        migrations.AddField(
            model_name='opponent',
            name='badge',
            field=models.ImageField(blank=True, default='default profile pic1.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='opponent',
            name='home',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='batting',
            name='match_format',
            field=models.ManyToManyField(to='home.MatchFormat'),
        ),
        migrations.AddField(
            model_name='bowling',
            name='match_format',
            field=models.ManyToManyField(to='home.MatchFormat'),
        ),
    ]
