# Generated by Django 3.1.5 on 2021-02-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210205_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='match_format',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.matchformat'),
        ),
        migrations.RemoveField(
            model_name='batting',
            name='opponent',
        ),
        migrations.AddField(
            model_name='batting',
            name='opponent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.opponent'),
        ),
        migrations.AlterField(
            model_name='bowling',
            name='match_format',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.matchformat'),
        ),
        migrations.RemoveField(
            model_name='bowling',
            name='opponent',
        ),
        migrations.AddField(
            model_name='bowling',
            name='opponent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.opponent'),
        ),
    ]
