# Generated by Django 3.1.5 on 2021-02-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210205_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.member'),
        ),
        migrations.AlterField(
            model_name='award',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.team'),
        ),
        migrations.AlterField(
            model_name='award',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.cup'),
        ),
        migrations.AlterField(
            model_name='batting',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.member'),
        ),
        migrations.AlterField(
            model_name='batting',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.team'),
        ),
        migrations.AlterField(
            model_name='bowling',
            name='member',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.member'),
        ),
        migrations.AlterField(
            model_name='bowling',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.team'),
        ),
    ]
