# Generated by Django 3.1.5 on 2021-02-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210205_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='batting',
            name='match_format',
        ),
        migrations.RemoveField(
            model_name='batting',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='batting',
            name='team',
        ),
        migrations.RemoveField(
            model_name='bowling',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bowling',
            name='match_format',
        ),
        migrations.RemoveField(
            model_name='bowling',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='bowling',
            name='team',
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('match_format', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.matchformat')),
                ('opponent', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.opponent')),
                ('team', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.team')),
            ],
        ),
        migrations.AddField(
            model_name='batting',
            name='match',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.match'),
        ),
        migrations.AddField(
            model_name='bowling',
            name='match',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.match'),
        ),
    ]
