# Generated by Django 3.1.5 on 2021-02-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210205_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='home',
            field=models.CharField(default='', max_length=20),
        ),
    ]
