# Generated by Django 3.1.5 on 2021-02-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0019_homepage_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Scorecard Page',
                'verbose_name_plural': 'Scorecard Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
