# Generated by Django 3.1.5 on 2021-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_scorecard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opponent',
            new_name='Club',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='home',
            new_name='home_venue',
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='banner_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
