# Generated by Django 3.1.5 on 2021-02-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210226_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinToss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='decision',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cointoss'),
        ),
    ]
