# Generated by Django 3.1.5 on 2021-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210226_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batting',
            old_name='out',
            new_name='mode_of_dismissal',
        ),
        migrations.RemoveField(
            model_name='bowling',
            name='extras',
        ),
        migrations.AddField(
            model_name='bowling',
            name='byes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bowling',
            name='leg_byes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bowling',
            name='no_balls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bowling',
            name='wides',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
