# Generated by Django 3.1.5 on 2021-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210226_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='overs_played',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
