# Generated by Django 3.1.5 on 2021-02-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210226_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='overs_played',
            new_name='ards_overs_batted',
        ),
        migrations.AddField(
            model_name='match',
            name='ards_wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_overs_batted',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
