# Generated by Django 3.1.5 on 2021-02-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210226_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointoss',
            name='decision',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
