# Generated by Django 3.1.5 on 2021-02-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20210226_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='batting',
            name='batter_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
