# Generated by Django 3.1.5 on 2021-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_batting_batter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowling',
            name='bowler_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
