# Generated by Django 3.1.5 on 2021-03-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_blogindexpage_blogpage_blogpagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
