# Generated by Django 3.1.5 on 2021-03-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='extras',
            name='ards',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
