# Generated by Django 3.1.5 on 2021-03-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20210305_1422'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='club',
            unique_together={('name', 'home_venue')},
        ),
    ]
