# Generated by Django 3.1.5 on 2021-03-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20210305_1432'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('team', 'date', 'opponent')},
        ),
    ]
