# Generated by Django 3.1.5 on 2021-03-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20210305_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extras',
            unique_together={('ards', 'match')},
        ),
    ]
