# Generated by Django 3.1.5 on 2021-03-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20210305_1439'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='award',
            unique_together={('type', 'team', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='cointoss',
            unique_together={('decision',)},
        ),
        migrations.AlterUniqueTogether(
            name='cup',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='matchformat',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='wicket',
            unique_together={('name',)},
        ),
    ]
