# Generated by Django 3.1.5 on 2021-03-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20210305_1500'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batting',
            unique_together={('batter_number', 'match')},
        ),
        migrations.AlterUniqueTogether(
            name='bowling',
            unique_together={('bowler_number', 'match')},
        ),
    ]
