# Generated by Django 3.1.5 on 2021-03-05 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20210305_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='batter_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bowling',
            name='bowler_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)]),
        ),
    ]
