# Generated by Django 3.1.5 on 2021-03-05 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20210305_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950)]),
        ),
    ]
