# Generated by Django 3.1.5 on 2021-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20210305_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowling',
            name='maidens',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
