# Generated by Django 3.1.5 on 2021-03-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_auto_20210305_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='batting',
            name='ards',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bowling',
            name='ards',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='batting',
            unique_together={('ards', 'batter_number', 'match')},
        ),
        migrations.AlterUniqueTogether(
            name='bowling',
            unique_together={('ards', 'bowler_number', 'match')},
        ),
    ]
