# Generated by Django 3.1.5 on 2021-03-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_auto_20210305_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='OppositionNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
    ]
