# Generated by Django 3.1.5 on 2021-03-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_oppositionnames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batting',
            name='out_by',
        ),
    ]
