# Generated by Django 3.1.5 on 2021-03-05 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_batting_out_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batting',
            unique_together={('batter_number', 'match')},
        ),
        migrations.RemoveField(
            model_name='batting',
            name='ards',
        ),
        migrations.CreateModel(
            name='BowlingOpponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowler_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)])),
                ('overs', models.IntegerField(blank=True, default=0, null=True)),
                ('runs', models.IntegerField(blank=True, default=0, null=True)),
                ('wickets', models.IntegerField(blank=True, default=0, null=True)),
                ('wides', models.IntegerField(blank=True, default=0, null=True)),
                ('no_balls', models.IntegerField(blank=True, default=0, null=True)),
                ('bowler_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.oppositionnames')),
                ('match', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.match')),
            ],
            options={
                'unique_together': {('bowler_number', 'match')},
            },
        ),
        migrations.CreateModel(
            name='BattingOpponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batter_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)])),
                ('runs', models.IntegerField(blank=True, default=0, null=True)),
                ('batter_name', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.oppositionnames')),
                ('match', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.match')),
                ('mode_of_dismissal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.wicket')),
                ('out_by', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.member')),
            ],
            options={
                'unique_together': {('batter_number', 'match')},
            },
        ),
    ]
