# Generated by Django 3.1.5 on 2021-03-31 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='decision',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cointoss'),
        ),
    ]
