# Generated by Django 3.1.5 on 2021-04-05 15:13

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0064_fixturepreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='store_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='store_link',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='store_text',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=100, null=True),
        ),
    ]
