# Generated by Django 3.1.5 on 2021-04-05 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0065_auto_20210405_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='store_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
