# Generated by Django 3.1.5 on 2021-04-05 15:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0067_auto_20210405_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheClubPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about', wagtail.core.fields.StreamField([('about', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add your Image', required=False)), ('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.CharBlock(help_text='Add your detail', required=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'The Club Page',
                'verbose_name_plural': 'The Club Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
