# Generated by Django 3.1.5 on 2021-04-05 15:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_theclubpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theclubpage',
            name='about',
            field=wagtail.core.fields.StreamField([('about', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add your Image', required=False)), ('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add your detail', required=False))]))], blank=True, null=True),
        ),
    ]
