# Generated by Django 3.1.5 on 2021-04-05 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0069_auto_20210405_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TheClubPage',
            new_name='TheClub',
        ),
    ]
