# Generated by Django 3.1.5 on 2021-04-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0073_customeruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
