# Generated by Django 3.1.5 on 2021-04-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0076_auto_20210407_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='weblink',
            new_name='website_link',
        ),
    ]
