# Generated by Django 3.1.5 on 2021-04-07 11:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0077_auto_20210407_1207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerUser',
            new_name='Profile',
        ),
    ]
