# Generated by Django 3.1.5 on 2021-04-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0078_auto_20210407_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ards_overs_batted',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ards_runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ards_wickets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_overs_batted',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_runs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent_wickets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
