# Generated by Django 3.1.5 on 2021-04-07 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_auto_20210407_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 4, 7, 15, 17, 51, 421216, tzinfo=utc), null=True),
        ),
    ]
