# Generated by Django 3.1.5 on 2021-04-07 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0083_auto_20210407_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 7, 15, 21, 1, 894941, tzinfo=utc), null=True),
        ),
    ]
