# Generated by Django 3.1.5 on 2021-04-07 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0089_auto_20210407_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bowling',
            name='bowler_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)]),
        ),
    ]
