# Generated by Django 3.1.5 on 2021-04-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0090_auto_20210407_1749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bowling',
            unique_together={('bowler_number', 'match')},
        ),
        migrations.RemoveField(
            model_name='bowling',
            name='ards',
        ),
    ]
