# Generated by Django 3.1.5 on 2021-04-08 14:09

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0093_auto_20210408_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheSport',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.core.fields.StreamField([('intro', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Add your Image', required=False)), ('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add your detail', required=False))]))], blank=True, null=True)),
                ('videos', wagtail.core.fields.StreamField([('video', wagtail.core.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock()), ('caption', wagtail.core.blocks.CharBlock(label='Caption', required=False)), ('float', wagtail.core.blocks.ChoiceBlock(choices=[('right', 'Right'), ('left', 'Left'), ('Center', 'Center')], label='Float', required=False)), ('size', wagtail.core.blocks.ChoiceBlock(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('half', 'Half')], label='Size', required=False))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'The Sport Page',
                'verbose_name_plural': 'The Sport Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
