# Generated by Django 3.1.5 on 2021-04-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0094_thesport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batting',
            unique_together={('member', 'batter_number', 'match')},
        ),
    ]
