# Generated by Django 3.1.5 on 2021-04-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0095_auto_20210408_1710'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batting',
            unique_together={('batter_number', 'match')},
        ),
    ]
