# Generated by Django 3.1.5 on 2021-04-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0097_auto_20210408_1712'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bowling',
            unique_together={('member', 'match'), ('bowler_number', 'match')},
        ),
    ]
