# Generated by Django 3.1.5 on 2021-04-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0102_auto_20210412_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(default='default profile pic1.png', upload_to=''),
        ),
    ]
