# Generated by Django 3.1.5 on 2021-04-16 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0105_auto_20210416_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingopponents',
            name='runs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='bowlingopponents',
            name='overs',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0.05)]),
        ),
        migrations.AlterField(
            model_name='bowlingopponents',
            name='runs',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
        ),
    ]
