# Generated by Django 3.1.5 on 2021-04-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_auto_20210416_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='ards',
            field=models.BooleanField(default=True),
        ),
    ]
