# Generated by Django 3.1.5 on 2021-04-26 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0114_auto_20210419_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingopponents',
            name='batter_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bowlingopponents',
            name='bowler_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)]),
        ),
    ]
